config/routes.rb
Polyglot::Application.routes.draw do
  resources :translation_services

  resources :term_requests

  get 'translate/:service/:from-:to/:term' => 'translate#show'

end

app/models/term_request.rb
class TermRequest < ActiveRecord::Base
end

app/models/translate.rb
class Translate < ActiveRecord::Base
end

app/models/translation_service.rb
class TranslationService < ActiveRecord::Base
  has_many :translation_service_languages
end

app/models/translation_service_language.rb
class TranslationServiceLanguage < ActiveRecord::Base
  belongs_to :translation_service
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/term_requests_controller.rb
class TermRequestsController < ApplicationController
  before_action :set_term_request, only: [:show, :edit, :update, :destroy]

  # GET /term_requests
  # GET /term_requests.json
  def index
    @term_requests = TermRequest.all
  end

  # GET /term_requests/1
  # GET /term_requests/1.json
  def show
  end

  # GET /term_requests/new
  def new
    @term_request = TermRequest.new
  end

  # GET /term_requests/1/edit
  def edit
  end

  # POST /term_requests
  # POST /term_requests.json
  def create
    @term_request = TermRequest.new(term_request_params)

    respond_to do |format|
      if @term_request.save
        format.html { redirect_to @term_request, notice: 'Term request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @term_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @term_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /term_requests/1
  # PATCH/PUT /term_requests/1.json
  def update
    respond_to do |format|
      if @term_request.update(term_request_params)
        format.html { redirect_to @term_request, notice: 'Term request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @term_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /term_requests/1
  # DELETE /term_requests/1.json
  def destroy
    @term_request.destroy
    respond_to do |format|
      format.html { redirect_to term_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term_request
      @term_request = TermRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_request_params
      params.require(:term_request).permit(:datetime, :term)
    end
end

app/controllers/translate_controller.rb
class TranslateController < ApplicationController
  # GET /translate
  # GET /translate.json
  def index
    @translates = Translate.all
  end

  # GET /translate/:service/:from-:to/:term
  # GET /translate/:service/:from-:to/:term.json
  def show
    service = TranslationService.find_by(name: params[:service])

    if service == nil then
      redirect_to raise ActionController::RoutingError.new("Service #{params[:service]} not found")
    end

    languages = service.translation_service_languages.find_by(
        source_language: params[:from],
        target_language: params[:to])

    if languages == nil then
      redirect_to raise ActionController::RoutingError.new("Service #{params[:service]} cannot translate from #{params[:from]} to #{params[:to]}")
    end

    entry = TermRequest.new(
        term: params[:term],
        source_language: languages.source_language,
        target_language: languages.target_language,
        service: service.name)

    entry.save

    formattedUrl = service.url
      .sub('{term}', entry.term)
      .sub('{from}', languages.source_language)
      .sub('{to}', languages.target_language)

    url = URI.parse(formattedUrl)
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http| http.request(req) }

    body = Nokogiri::HTML::Document.parse(res.body)
    data = body.css('div.js-article-lingvo')
    data.each do |node|
      puts node
    end

  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def translate_params
      params[:translate]
    end
end

app/controllers/translation_services_controller.rb
class TranslationServicesController < ApplicationController
  before_action :set_translation_service, only: [:show, :edit, :update, :destroy]

  # GET /translation_services
  # GET /translation_services.json
  def index
    @translation_services = TranslationService.all
  end

  # GET /translation_services/1
  # GET /translation_services/1.json
  def show
  end

  # GET /translation_services/new
  def new
    @translation_service = TranslationService.new
  end

  # GET /translation_services/1/edit
  def edit
  end

  # POST /translation_services
  # POST /translation_services.json
  def create
    @translation_service = TranslationService.new(translation_service_params)

    respond_to do |format|
      if @translation_service.save
        format.html { redirect_to @translation_service, notice: 'Translation service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @translation_service }
      else
        format.html { render action: 'new' }
        format.json { render json: @translation_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translation_services/1
  # PATCH/PUT /translation_services/1.json
  def update
    respond_to do |format|
      if @translation_service.update(translation_service_params)
        format.html { redirect_to @translation_service, notice: 'Translation service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @translation_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translation_services/1
  # DELETE /translation_services/1.json
  def destroy
    @translation_service.destroy
    respond_to do |format|
      format.html { redirect_to translation_services_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translation_service
      @translation_service = TranslationService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translation_service_params
      params.require(:translation_service).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translation_services_helper.rb
module TranslationServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polyglot</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/term_requests/_form.html.erb
<%= form_for(@term_request) do |f| %>
  <% if @term_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term_request.errors.count, "error") %> prohibited this term_request from being saved:</h2>

      <ul>
      <% @term_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <div class="field">
    <%= f.label :term %><br>
    <%= f.text_field :term %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/term_requests/edit.html.erb
<h1>Editing term_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @term_request %> |
<%= link_to 'Back', term_requests_path %>

app/views/term_requests/index.html.erb
<h1>Listing term_requests</h1>

<table>
  <thead>
    <tr>
      <th>Datetime</th>
      <th>Term</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @term_requests.each do |term_request| %>
      <tr>
        <td><%= term_request.datetime %></td>
        <td><%= term_request.term %></td>
        <td><%= link_to 'Show', term_request %></td>
        <td><%= link_to 'Edit', edit_term_request_path(term_request) %></td>
        <td><%= link_to 'Destroy', term_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Term request', new_term_request_path %>

app/views/term_requests/new.html.erb
<h1>New term_request</h1>

<%= render 'form' %>

<%= link_to 'Back', term_requests_path %>

app/views/term_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datetime:</strong>
  <%= @term_request.datetime %>
</p>

<p>
  <strong>Term:</strong>
  <%= @term_request.term %>
</p>

<%= link_to 'Edit', edit_term_request_path(@term_request) %> |
<%= link_to 'Back', term_requests_path %>

app/views/translate/_form.html.erb
<%= form_for(@translate) do |f| %>
  <% if @translate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translate.errors.count, "error") %> prohibited this translate from being saved:</h2>

      <ul>
      <% @translate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/translate/index.html.erb
<h1>Listing translates</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @translates.each do |translate| %>
      <tr>
        <td><%= link_to 'Show', translate %></td>
        <td><%= link_to 'Edit', edit_translate_path(translate) %></td>
        <td><%= link_to 'Destroy', translate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Translate', new_translate_path %>

app/views/translate/show.html.erb
<p id="notice"><%= notice %></p>

<p> HELLO </p>

app/views/translation_services/_form.html.erb
<%= form_for(@translation_service) do |f| %>
  <% if @translation_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translation_service.errors.count, "error") %> prohibited this translation_service from being saved:</h2>

      <ul>
      <% @translation_service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/translation_services/edit.html.erb
<h1>Editing translation_service</h1>

<%= render 'form' %>

<%= link_to 'Show', @translation_service %> |
<%= link_to 'Back', translation_services_path %>

app/views/translation_services/index.html.erb
<h1>Listing translation_services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @translation_services.each do |translation_service| %>
      <tr>
        <td><%= translation_service.name %></td>
        <td><%= translation_service.url %></td>
        <td><%= link_to 'Show', translation_service %></td>
        <td><%= link_to 'Edit', edit_translation_service_path(translation_service) %></td>
        <td><%= link_to 'Destroy', translation_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Translation service', new_translation_service_path %>

app/views/translation_services/new.html.erb
<h1>New translation_service</h1>

<%= render 'form' %>

<%= link_to 'Back', translation_services_path %>

app/views/translation_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @translation_service.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @translation_service.url %>
</p>

<%= link_to 'Edit', edit_translation_service_path(@translation_service) %> |
<%= link_to 'Back', translation_services_path %>